### ISSUE TITLE
more scripts

### ISSUE THREAD

**Issue by micuentadecasa** [alulsh/SharePoint-2013-STIGs#1]
Hi Alexandra, I would like to know if you have more scripts or know where I can found them
?, I have found about 39 issues in the stig for sharepoint and in your scripts only appear three of them...

**Comment by alulsh** [comment]
Hi @micuentadecasa,

Unfortunately, these are all the SharePoint STIG scripts I developed. I welcome any pull requests to add more scripts!

I no longer work with SharePoint professionally so it is unlikely I will write or develop any more scripts.

**Comment by micuentadecasa** [comment]
Thanks @alulsh , great job.

**Comment by alulsh** [comment]
Closing this issue as I will be archiving this repository (https://github.com/alulsh/SharePoint-2013-STIGs/commit/31771fe6ee761e4ec6f8184cd93b57c75a396380).
